## Sachin Tendulkar's ODIs for India
(Source: [cricinfo](https://stats.espncricinfo.com/ci/engine/player/35320.html?class=2;template=results;type=batting;view=innings))

#### Imports

In [1]:
import numpy as np
import pandas as pd

#### Read the data

In [4]:
df_sachin = pd.read_csv("Sachin_ODI.csv")
df_sachin.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

#### What is the probability of India winning when Sachin is playing?

In [6]:
num_won = len(df_sachin[df_sachin["Won"] == True])
num_matches = len(df_sachin)

p_win = num_won / num_matches

print(f"Prob that india wins when sachin plays: {p_win}")

Prob that india wins when sachin plays: 0.5111111111111111

#### What is the probability of Sachin scoring a century?

In [8]:
num_century = len(df_sachin[df_sachin["century"] == True])
num_matches = len(df_sachin)

p_century = num_century / num_matches

print(f"Prob that sachin scores a century: {p_century}")

Prob that sachin scores a century: 0.12777777777777777

#### What is the probability of Sachin scoring a century and India winning?

In [9]:
num_century_and_win = len(df_sachin[ (df_sachin["Won"] == True) & (df_sachin["century"] == True)])
num_matches = len(df_sachin)

p_won_and_century = num_century_and_win / num_matches

print(f"Prob that sachin scores a century and india wins: {p_won_and_century}")

Prob that sachin scores a century and india wins: 0.08333333333333333

In [10]:
num_century_and_win = len(df_sachin[ (df_sachin["Won"] == False) & (df_sachin["century"] == True)])
num_matches = len(df_sachin)

p_won_and_century = num_century_and_win / num_matches

print(f"Prob that sachin scores a century and india wins: {p_won_and_century}")

Prob that sachin scores a century and india wins: 0.044444444444444446

In [11]:
pd.crosstab(index = df_sachin["century"], columns = df_sachin["Won"], margins = True)

Won      False  True  All
century
False      160   154  314
True        16    30   46
All        176   184  360

In [12]:
30/360

0.08333333333333333

In [13]:
16/360

0.044444444444444446